### ISSUE TITLE
use this icon for article in a periodical

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#33] opened 2016-05-25 14:24 UTC
![journalarticle](https://cloud.githubusercontent.com/assets/17299921/15543350/23b626dc-225a-11e6-9854-9ce5e41631f0.png)

These appear to be peer reviewed as well so use the same graphic (see attached)

**Comment by srickel1** [comment] 2016-05-25 14:28
cover images are retrieved based on the format of the record.  Please provide examples of the record so we can match it up.

**Comment by srickel1** [comment] 2016-05-25 14:29
duplicate of another ticket so closing

**Closed as completed** 2016-05-25 14:29 UTC
Labels: wontfix
