### ISSUE TITLE
add a-z list option

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#26] opened 2016-04-26 14:26 UTC
Can you think of a way to get a searchable version of this added:
http://library.unl.edu/search/?searchtype=y&SORT=D&searcharg=*

**Comment by srickel1** [comment] 2016-04-26 14:53
Do you mean to index the eresources?  Haven't we already discussed this?  Duplicate of #6

**Comment by dallison1** [comment] 2016-04-26 15:08
No, I'm wondering if there is a better way to integrate this information - a complete list instead of using the e-resources page.  Since that can't be harvested this might be an alternate way to integrate the individual titles.

**Comment by srickel1** [comment] 2016-10-26 15:20
done with Mike's update to show subject facets on front page.

**Closed as completed by srickel1** 2016-10-26 15:20 UTC
Labels: enhancement, question
