### ISSUE TITLE
icon for column/opinions in ebsco results

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#32] opened 2016-05-25 14:19 UTC
![opinion](https://cloud.githubusercontent.com/assets/17299921/15543210/abfd904e-2259-11e6-9915-f01b677c891f.png)

Use this icon when column/opinion is the format.

**Comment by srickel1** [comment] 2016-05-25 14:30
cover images are retrieved based on the format of the record.  Please provide examples of the record so we can match it up.  This is a duplicate of the original ticket for icons #30.  Please add comments and additional requests to that ticket.

**Closed as completed by srickel1** 2016-05-25 14:30 UTC
